spring.application.name=giybat.uz
################################################
#                Database                      #
################################################
spring.datasource.url=jdbc:postgresql://localhost:5432/giybat_uz
spring.datasource.username=giybat
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
################################################
#                   Email                      #
################################################
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=bmuxammadov1@mail.ru
spring.mail.password=2WGVqtz2Mg5Iz3mUyf1F
spring.mail.protocol=smtps

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000
